# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT0012 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.0.12"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.12/teller_v0.0.12_darwin_amd64.tar.gz"
      sha256 "3426e8447186436ee4f7334ee0111fcf18f7dd36a5b57d8b6e968544049298a5"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.12/teller_v0.0.12_darwin_arm64.tar.gz"
      sha256 "264dd9aa5125bd279cf792e83326495ef6c1dc16c0fa0a5065595470dd07609e"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.12/teller_v0.0.12_linux_amd64.tar.gz"
      sha256 "5ace8c931356d0c592323d5894c16dcbe6c24f481e5f450ba2284d7537802bef"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.12/teller_v0.0.12_linux_arm64.tar.gz"
      sha256 "248f7e2f4b6830434a7abd5d894c0d7b6c988000346e39b18e1135eb4be843d8"

      def install
        bin.install "teller"
      end
    end
  end
end
