# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT010 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.1.0/teller_v0.1.0_darwin_amd64.tar.gz"
      sha256 "0fc55bb18cea9559a344fe1e5014f6d6272098373e49954697105492eb11066f"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashhavoc/teller/releases/download/v0.1.0/teller_v0.1.0_darwin_arm64.tar.gz"
      sha256 "00456b09003d3def74996d5fb8b6d720a95c04ab65573db711ce000b7b97e1fc"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.1.0/teller_v0.1.0_linux_amd64.tar.gz"
      sha256 "dabeb54339e9dd27893f3e34365d6da561f91138e514ca1c4cda1ebd777cc8e6"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashhavoc/teller/releases/download/v0.1.0/teller_v0.1.0_linux_arm64.tar.gz"
      sha256 "665e87b5ae38a19677c65bc153f64f65712a2a7cfe76451dab829eccfb866552"

      def install
        bin.install "teller"
      end
    end
  end
end
