# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT0021 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.0.21"

  on_macos do
    on_intel do
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.21/teller_v0.0.21_darwin_amd64.tar.gz"
      sha256 "b93852412b32ab83a6c1f1b93989e4e5270e0e2e489f6577eb43cecfe39bda7e"

      def install
        bin.install "teller"
      end
    end
    on_arm do
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.21/teller_v0.0.21_darwin_arm64.tar.gz"
      sha256 "3a189f384208441557bb89395e8bcac55cfa526214c2822f67c8e06251f167d3"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.0.21/teller_v0.0.21_linux_amd64.tar.gz"
        sha256 "308c4045b8039ceda9d3530111208920197ef7922c6b3f1e8bb676ad4e46d408"

        def install
          bin.install "teller"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.0.21/teller_v0.0.21_linux_arm64.tar.gz"
        sha256 "35cb7068b2ffc5dcc6106b2a2c5715a099b31afe06559bed16a924ae1d860223"

        def install
          bin.install "teller"
        end
      end
    end
  end
end
