# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT006 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.0.6"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.6/teller_v0.0.6_darwin_amd64.tar.gz"
      sha256 "ec9dbd1026a2f7ad7125f427ec87a9b6a0f4d2c6b88cce682ae4303f87c66d9e"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.6/teller_v0.0.6_darwin_arm64.tar.gz"
      sha256 "bcb137677a0a8b04a199b92135a18c9c1c2a8865bf9278cc3b1fa70695777812"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.6/teller_v0.0.6_linux_amd64.tar.gz"
      sha256 "7c80b23cc5b97e2e7b392c61ff4a648558cdf9bea5dff1b389175f26fa659d5b"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.6/teller_v0.0.6_linux_arm64.tar.gz"
      sha256 "d47d70c9222a0104d3faa03ea6255879a81b4830b09b82e6ce64ec1a90236d10"

      def install
        bin.install "teller"
      end
    end
  end
end
