# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teller < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.0.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.8/teller_v0.0.8_darwin_amd64.tar.gz"
      sha256 "73a30ddaf224844df60b9ae3ad2d88a2f02d87d09df64ce2fa0e966428c3d13f"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.8/teller_v0.0.8_darwin_arm64.tar.gz"
      sha256 "2ffc6e0b1da95784ea40393b90d6b7f555e75e58d9331dbe5b73ccf5e32564a4"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.8/teller_v0.0.8_linux_amd64.tar.gz"
      sha256 "697cdc47f6f90b158df0805407251b33053a24cd8362e30d024d228a3ce75a5f"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.8/teller_v0.0.8_linux_arm64.tar.gz"
      sha256 "c8ebaaad9ca0f14068d4ae0386c1249229cafcd775e5425bb7243da0355c1903"

      def install
        bin.install "teller"
      end
    end
  end
end
