# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Teller < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.2.2"

  on_macos do
    on_intel do
      url "https://github.com/hashhavoc/teller/releases/download/v0.2.2/teller_v0.2.2_darwin_amd64.tar.gz"
      sha256 "6a4e4a212a0a11e6863ad1a7b30bf940445959e237b4235efa505372df972b42"

      def install
        bin.install "teller"
      end
    end
    on_arm do
      url "https://github.com/hashhavoc/teller/releases/download/v0.2.2/teller_v0.2.2_darwin_arm64.tar.gz"
      sha256 "ecf9a50e580ecdf77db86299aa2209bf29acd30dcefc0e1904a67f035a4df04d"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.2.2/teller_v0.2.2_linux_amd64.tar.gz"
        sha256 "b88c8c4e3be399ec5c218849486eae0ad125deb75ae532344165ab905cb24455"

        def install
          bin.install "teller"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.2.2/teller_v0.2.2_linux_arm64.tar.gz"
        sha256 "9c22b9ca6d787f1814f3ac4c6de2d05fa8fee138574ac5cd215006e1b6b96271"

        def install
          bin.install "teller"
        end
      end
    end
  end
end
