# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT0017 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.0.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.17/teller_v0.0.17_darwin_amd64.tar.gz"
      sha256 "25b6886ce8e42a001486aa0285a0ccc2fdb54a62a7005211d35dd8756e1c5f9a"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.17/teller_v0.0.17_darwin_arm64.tar.gz"
      sha256 "3400ce0c1700cde2d854f7da16bd58ca0e0c65b01142697964ab1cae4813c77b"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.17/teller_v0.0.17_linux_amd64.tar.gz"
      sha256 "1e0205a7888608a4c37e6a7ff3babf3bd5442d184bde379f07e9fc0315b63e30"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.17/teller_v0.0.17_linux_arm64.tar.gz"
      sha256 "696bea17513b29b8967e38602eb9e4c428ed2d6591845dd8328029b731a7e8ba"

      def install
        bin.install "teller"
      end
    end
  end
end
