# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT0016 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.0.16"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.16/teller_v0.0.16_darwin_amd64.tar.gz"
      sha256 "09d08aebd3dd4594aa6343dd30e5a90fea1dc9cd4e938b4c06bbc9d52bd7c224"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.16/teller_v0.0.16_darwin_arm64.tar.gz"
      sha256 "acf8759979f75e34c384bc4ae73d5c34ac4e277deb507bc4e594d6d984b89c7e"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.16/teller_v0.0.16_linux_amd64.tar.gz"
      sha256 "dd891f2f0cee33c6716ca4160cbf9ec9040569ef569a978f6cd2f72a39c85e6f"

      def install
        bin.install "teller"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.16/teller_v0.0.16_linux_arm64.tar.gz"
      sha256 "ded335c5723fccdb6a1c271cbc7aa4edd806059f54cd6fb2a88260b91d719355"

      def install
        bin.install "teller"
      end
    end
  end
end
