# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT011 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.1.1"

  on_macos do
    on_intel do
      url "https://github.com/hashhavoc/teller/releases/download/v0.1.1/teller_v0.1.1_darwin_amd64.tar.gz"
      sha256 "9739c10557d5238711ef58a234dc412987f0900f58efbd795e52badf707ce7fb"

      def install
        bin.install "teller"
      end
    end
    on_arm do
      url "https://github.com/hashhavoc/teller/releases/download/v0.1.1/teller_v0.1.1_darwin_arm64.tar.gz"
      sha256 "c97e603dd1abcfeea3133e7749a4dfae6ae19b5e6ef68e3039ecdf3e0646976e"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.1.1/teller_v0.1.1_linux_amd64.tar.gz"
        sha256 "0aba9bf172d145315e571bf4fc743db1d4948b32e38629ffbd093cd69e74e2a5"

        def install
          bin.install "teller"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.1.1/teller_v0.1.1_linux_arm64.tar.gz"
        sha256 "4091c490e8bf08aab2c12798668f1443fc6932a0b92e4cf3cc33bffd18814be5"

        def install
          bin.install "teller"
        end
      end
    end
  end
end
