# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TellerAT0023 < Formula
  desc "CLI for STX"
  homepage "https://github.com/hashhavoc/teller"
  version "0.0.23"

  on_macos do
    on_intel do
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.23/teller_v0.0.23_darwin_amd64.tar.gz"
      sha256 "6a12900ad4de767879dd4d20c3351d35189b8c03a536c8b3fb570f290eb1430d"

      def install
        bin.install "teller"
      end
    end
    on_arm do
      url "https://github.com/hashhavoc/teller/releases/download/v0.0.23/teller_v0.0.23_darwin_arm64.tar.gz"
      sha256 "92bca1c8109fcde26f378ef66f0faa63e3f3cbcf6fa8295954e69646121935cf"

      def install
        bin.install "teller"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.0.23/teller_v0.0.23_linux_amd64.tar.gz"
        sha256 "0e08f4b1c9c851e9aff9cc9710b9ae4b033d17c9f6ea80e99931dca2724d272f"

        def install
          bin.install "teller"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/hashhavoc/teller/releases/download/v0.0.23/teller_v0.0.23_linux_arm64.tar.gz"
        sha256 "9ece64fec794e414c45e8b8b097f5d8a34c55daed6921efeff803e356680e908"

        def install
          bin.install "teller"
        end
      end
    end
  end
end
